---
name: "RandomSorter"
guid: "9eda27ec-6e19-41ff-89e6-cabeebaf3b14"
version: "1.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
overview: "Add random sorting option"
description: >
  For very lazy sunday
category: "General"
owner: "edupuis"
artifacts:
- "RandomSorter.dll"
changelog: >
  changelog
